# Generated by Django 5.2.4 on 2025-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("doctor", "Doctor"), ("patient", "Patient")],
                default="patient",
                max_length=10,
                null=True,
            ),
        ),
    ]
