# Generated by Django 5.2.4 on 2025-09-01 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="patient_images"),
                ),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.TextField(blank=True, max_length=1000, null=True)),
                ("gender", models.CharField(blank=True, max_length=150, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "blood_group",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Appointment Scheduled", "Appointment Scheduled"),
                            ("Appointment Cancelled", "Appointment Cancelled"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointments",
                        to="base.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date"],
            },
        ),
    ]
