# Generated by Django 5.2.4 on 2025-07-28 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("doctor", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billings",
                to="base.appointment",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_tests",
                to="base.appointment",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_record",
                to="base.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.appointment"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="available_doctors",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="doctor.doctor"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="base.service",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("appointment_id", "doctor", "appointment_date"),
                name="unique_appointment_per_doctor_per_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("appointment_id", "doctor", "appointment_date")},
        ),
    ]
