# Generated by Django 5.2.4 on 2025-09-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="service",
            managers=[],
        ),
    ]
