# Generated by Django 5.2.4 on 2025-09-01 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_alter_doctor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="next_availability",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
